@startuml
participant "Any integration"
participant Webserver
actor User
participant "Telegram Bot"
database Redis
database PostgreSQL
participant RabbitMQ
participant Consumer
participant Grafana


title [C1]: TO BE

"Any integration" -> Webserver: POST-запрос
User -> "Telegram Bot": Взаимодействие
"Telegram Bot" -> Redis: Чтение кэша
alt Кэш найден в Redis
    Redis --> "Telegram Bot": Данные из кэша
else Кэш не найден в Redis
    "Telegram Bot" -> PostgreSQL: Запрос данных
    PostgreSQL --> "Telegram Bot": Данные из базы
    "Telegram Bot" -> Redis: Запись в кэш
end

alt HTTP_200_OK
    Webserver -> RabbitMQ: Отправка сообщения в очередь 1
else Any error
    Webserver -> "Any integration": Сообщение об ошибке
end
"Telegram Bot" -> RabbitMQ: Отправка сообщения в очередь 2
RabbitMQ -> Consumer: Получение сообщения
Consumer -> "Telegram Bot": Отправка ответа
"Telegram Bot" -> Grafana: Логирование
"Any integration" -> Grafana: Логирование
@enduml
